export const textos = {
    ing_edson_raymundo: 'Ingeniero Electricista con Maestría en Gestión de Mercados Eléctricos. Analista de regulación y normativa en Asociación de Cogeneradores Independientes de Guatemala — Julio 2017-Actualidad. Análisis de la normativa nacional (LGE, RLGE, RAAM, Normas de Coordinación Operativa y Comercial) y regional (RMER). Participación en cambios normativos en el Mercado Mayorista de Guatemala y Mercado Eléctrico Regional.'+
    'Administrador del Mercado Mayorista - Noviembre 2013-Junio 2017. Planificación de corto plazo de la operación del sistema eléctrico de Guatemala, manejo y procesamiento de información y base de datos para la operación del mercado eléctrico nacional y regional.'+
    'Auxiliar de cátedra, Departamento de Matemática, Facultad de Ingeniería, Universidad de San Carlos de Guatemala - Junio 2012-Octubre 2013'
    ,
    ing_sergio_kestler: `Ingeniero Mecánico Electricista e Ingeniero Infieri Electricista. Magíster en Administración Financiera. Especialización en Gerencia de Mantenimiento Eléctrico y Subestaciones Eléctricas. Certificado en Habilitaciones y Transacciones Comerciales y en Coordinación de la Operación. SCRUM MASTER. Profesional especializado con más de 8 años de experiencia en el sector eléctrico de Guatemala, inmerso en labores de planeación del despacho hidrotérmico, transmisión de energía en alta tensión, distribución en MT/BT así como en actividades de telecontrol y monitoreo del la red vía SCADA. Instituciones: Ministerio de Energía y Minas (MEM), Escuela de Ingeniería Mecánica Eléctrica (FIUSAC),ENERGUATE, Facultad de Ingeniería UPANA y TRECSA .`
    ,
    ing_gabriel_velasquez: `Tiene más de 10 años de experiencia en el sector energético de la región centroamericana, desenvolviéndose como ingeniero mecánico electricista. Actualmente funge como director técnico de Planeación Energético-Minero – UPEM-, en el ministerio de Energía Minas de Guatemala, se encuentra en el ministerio desde el año 2012. Ha sido ejecutor de proyectos para varios organismos internacionales en temas energéticos, siendo estos IRENA, OLADE, CEPAL, HIVOS, PM, BID, BM, CECACIER, OEA, GIZ, BGR, SICA, PSR y otros. Desde 2014 ha sido docente de varios cursos de ingeniería, arquitectura, economía, política y energía, tanto en pregrado como en postgrado. Tiene un MBA en Digital Business de la Universidad de Cádiz, España y una maestría de administración en Administración Industrial y Empresas de Servicios,en Guatemala.`
    ,
    ing_marco_baten: 'Ingeniero en Sistemas de Información y Ciencias de la Computación Universidad Mariano'+
    'Gálvez de Guatemala, 2011. Magister en Informática Forense y Seguridad de la Información. Universidad Galileo de Guatemala, 2020. Vicepresidente del Grupo Regional de Comisión de Estudio 20 sobre Internet de las Cosas y Ciudades y Comunidades Inteligentes (Unión Internacional de Telecomunicaciones). 18 de julio de 2022 a la fecha. Presidente de la Junta Directiva de la Comisión Técnica Regional de Telecomunicaciones. 22 de julio de 2022 a la fecha. Vicepresidente de la Junta Directiva de la Comisión Técnica Regional de Telecomunicaciones. 22 de julio de 2021 al 21 de julio de 2022.'
}